### ISSUE TITLE
Body of message is not written in second call to `Write`

### ISSUE THREAD

**Issue by inliquid** [wneessen/go-mail#8]
Just found an interesting issue. In my scenario I first call `Msg.Write` to log message contents to debug logger and after that `Msg.WriteToSendmailWithContext` does not populate body of the message. Removing first call to `Msg.Write` or making two sequential calls to `Msg.Write` proves that. It seems that underlying writer shifts its current position to the end of buffer preventing body from being read second time. In original `gomail` this works normally. Didn't have much time to look into it.

**Comment by wneessen** [comment]
Thanks for the report. You are right... we were using `io.Copy` to write to the body string/alternative string to the io.Writer. This placed the byte position of the buffer to be at the EOF after the first `WriteTo()` call leaving the output of a 2nd call to `WriteTo()` empty. 

This has now been fixed with https://github.com/wneessen/go-mail/commit/c001ac5b94a8eb2d6154845efd41418a3de24b2e
